# Generated by Django 5.2.12 on 2026-03-20 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Creación"),
                            ("update", "Actualización"),
                            ("delete", "Eliminación"),
                            ("status_change", "Cambio de estado"),
                            ("comment", "Comentario"),
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="entidad"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID del objeto"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-created_at"],
            },
        ),
    ]
